//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCadastroEstagio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONE
    {
        public int ID { get; set; }
        public Nullable<int> CLIENTE_ID { get; set; }
        public string DDD { get; set; }
        public string TELEFONE1 { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
